# Generated by Django 4.2.1 on 2023-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='city',
            field=models.CharField(default='Bangalore', max_length=20),
        ),
    ]
